### ISSUE TITLE
Duplicate ALLURE_CRYPTO_PASSWORD in Deployments

### ISSUE THREAD

**Issue by dyurchenko-whoosh** [qameta/helm-charts#26]
Hi,

In [docs](https://docs.qameta.io/allure-testops/migrations/to-3-184-2/)  values `ALLURE_CRYPTO_PASSWORD` set in value  `uaa.env.secret` and `report.env.secret`, which after running helm appear in Deployment template:
```
<cut>
          - name: "ALLURE_CRYPTO_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: allure-ee-allure-ee
                key: "uaa.ALLURE_CRYPTO_PASSWORD"
<cut>
```
And same for report:
```
<cut>
          - name: "ALLURE_CRYPTO_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: allure-ee-allure-ee
                key: "report.ALLURE_CRYPTO_PASSWORD"
<cut>
```

In commit 9fb927deaff9fd9533f8f65fefabf8fc05d10b90 you add env `ALLURE_CRYPTO_PASSWORD` with different key ref:
```
+         - name: "ALLURE_CRYPTO_PASSWORD"
+           valueFrom:
+             secretKeyRef:
+               name: allure-ee-allure-ee
+               key: "password"
```

So in resulting Deployment template duplicates are occurred with name `ALLURE_CRYPTO_PASSWORD` and different refs:
```diff
$ helm diff upgrade --reuse-values allure-ee qameta/allure-ee
<cut>
          - name: "SPRING_SESSION_STORE_TYPE"
            value: "REDIS"
+         - name: "ALLURE_CRYPTO_PASSWORD"
+           valueFrom:
+             secretKeyRef:
+               name: allure-ee-allure-ee
+               key: "password"
          - name: "ALLURE_BLOBSTORAGE_S3_ACCESSKEY"
            valueFrom:
              secretKeyRef:
                name: allure-ee-allure-ee
                key: "report.ALLURE_BLOBSTORAGE_S3_ACCESSKEY"
          - name: "ALLURE_BLOBSTORAGE_S3_SECRETKEY"
            valueFrom:
              secretKeyRef:
                name: allure-ee-allure-ee
                key: "report.ALLURE_BLOBSTORAGE_S3_SECRETKEY"
          - name: "ALLURE_CRYPTO_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: allure-ee-allure-ee
                key: "report.ALLURE_CRYPTO_PASSWORD"
          - name: "ALLURE_REDIS_NAMESPACE"
            valueFrom:
              secretKeyRef:
                name: allure-ee-allure-ee
                key: "report.ALLURE_REDIS_NAMESPACE"
<cut>
```
